### PR TITLE
Add "Serverless Vector Tiles on AWS" article

### PR DESCRIPTION
**Pull request by kylebarron**
I found this tutorial super helpful for hosting vector tiles on S3.

### CODE REVIEW

**Comment by f7o** [comment]
As i am a expert in cloud technologies i like this solution, but i do not see the vector tile specific parts.

It is just a tutorial how to use S3, CloudFront and other services from AWS to serve files using AWS as a CDN.

Please explain your thoughts more detailed, why it is VT specific know how.

**Comment by kylebarron** [comment]
I thought it was similar enough to "Build Your Own Static Vector Tile Pipeline" to be included, since even though it's a tutorial about S3, the focus is on vector tiles, but I agree it doesn't have details on specifically building the tiles, since it grabs them from OpenMapTiles.

You can close this if you don't think it should be included.

**Comment by f7o** [comment]
I see your point, i would actually put the repo link instead of this direct pdf link. Do see an issue to o this change?
In my opion its better, cause one will see the origin of the pdf (in this case a github repo).

**Comment by kylebarron** [comment]
Either way is fine with me

**Comment by f7o** [comment]
I cannot do the change on your repo, so just put the github repo link instead and i merge it

**Comment by kylebarron** [comment]
I just updated the link

**Pull request merged**
